import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.scss";

const kanit = Kanit({ subsets: ["latin"], weight: ['300','400','500','600', '700','800','900'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        {children}
        <ToastContainer hideProgressBar />
      </body>
    </html>
  );
}
